server.port=8082
server.address=0.0.0.0

spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/RDV-Prise-containerdb}
spring.datasource.username=${JDBC_DATABASE_USERNAME:postgres}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:Salim1011}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
