sonar.projectKey=rdv-management
sonar.projectName=RDV Management
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000

sonar.sources=backend/Stage-Marsa-RDV-Management-backend/src/main/java,backend/Stage-Marsa-RDV-Management-backend/src/main/resources,frontend/src
sonar.tests=backend/Stage-Marsa-RDV-Management-backend/src/test/java
sonar.java.binaries=backend/Stage-Marsa-RDV-Management-backend/target/classes
sonar.java.test.binaries=backend/Stage-Marsa-RDV-Management-backend/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=backend/Stage-Marsa-RDV-Management-backend/target/site/jacoco/jacoco.xml

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.log,**/coverage/**,**/.dockerignore,**/Dockerfile
sonar.test.exclusions=frontend/**,**/target/**
sonar.sourceEncoding=UTF-8
